# Generated by Django 4.1.2 on 2023-07-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='Иконки')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('file_tgs', models.FileField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('id_user', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.IntegerField(null=True)),
                ('id_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='Bot.add_item')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
