# Generated by Django 4.1.2 on 2023-07-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_remove_bot_id_items_orderfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfood',
            name='order_food',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='order_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.add_item'),
        ),
    ]
