# Generated by Django 4.1.2 on 2023-07-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_remove_orderfood_order_food_orderfood_order_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='id_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='Bot.orderfood'),
        ),
    ]
