# Generated by Django 4.1.2 on 2023-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_bot_id_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='order_food',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
