# Generated by Django 4.1.2 on 2023-07-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_alter_orderfood_order_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='id_items',
        ),
        migrations.AddField(
            model_name='bot',
            name='OrderFood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.orderfood'),
        ),
    ]
