# Generated by Django 4.1.2 on 2023-07-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_remove_bot_id_items_bot_orderfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='OrderFood',
            new_name='orderfood',
        ),
    ]
