# Generated by Django 4.1.2 on 2023-07-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_rename_orderfood_bot_orderfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='orderfood',
            new_name='order_food',
        ),
    ]
