# Generated by Django 4.1.2 on 2023-07-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_author_diary_photo_remove_bot_order_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
