# Generated by Django 4.1.2 on 2023-07-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_remove_photo_author_delete_author_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='diary',
            new_name='bot',
        ),
    ]
