# Generated by Django 4.1.2 on 2023-07-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0011_rename_diary_bot_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='bot',
            new_name='diary',
        ),
    ]
