# Generated by Django 4.1.2 on 2023-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0013_diary_add_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='order_food',
        ),
        migrations.AddField(
            model_name='diary',
            name='order_food_id',
            field=models.IntegerField(null=True),
        ),
    ]
