# Generated by Django 4.1.2 on 2023-07-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bot', '0015_remove_diary_order_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
