# Generated by Django 4.1.2 on 2023-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0017_alter_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
