# Generated by Django 4.1.2 on 2023-07-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0019_diary_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='diary',
        ),
    ]
