# Generated by Django 4.1.2 on 2023-07-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0020_remove_bot_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.diary'),
        ),
    ]
