# Generated by Django 4.1.2 on 2023-07-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0021_bot_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='diary',
        ),
    ]
