# Generated by Django 4.1.2 on 2023-07-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0022_remove_bot_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('add_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.add_item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.bot')),
            ],
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
