# Generated by Django 4.1.2 on 2023-08-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0023_orderitem_delete_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='order_choice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_diaries', to='Bot.bot'),
        ),
    ]
