# Generated by Django 3.2.19 on 2023-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0025_auto_20230817_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
